### ISSUE TITLE
Octokit.projects.createForRepo throws a 404 Not Found

### ISSUE THREAD

**Issue by taarushv** [octokit/octokit.js#1214]
I was using rest.js for my react app but I was having trouble creating repos. Ported the code to Node to debug it. 

```
const octokit = require('@octokit/rest')
const Octokit = new octokit({
    headers:{
        accept:'application/vnd.github.inertia-preview+json'
    }
})
const main = async () => {
    await Octokit.authenticate({
        type: 'token',
        token: <my token here>
    })

    Octokit.projects.createForRepo({
        owner:'taarushv',
        name:<repo name>,
        repo:<repo name>
    }).then(result =>{
        console.log(result)
    }).catch(err => {
        console.log(err);
    })
}

main()
```

Here's the error log:

```
{ HttpError: Not Found
    at response.text.then.message (/Users/TaarushV/Desktop/code/debug/node_modules/@octokit/request/lib/request.js:55:27)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  name: 'HttpError',
  status: 404,
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
     connection: 'close',
     'content-encoding': 'gzip',
     'content-security-policy': "default-src 'none'",
     'content-type': 'application/json; charset=utf-8',
     date: 'Mon, 21 Jan 2019 10:08:32 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '404 Not Found',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'transfer-encoding': 'chunked',
     'x-accepted-oauth-scopes': 'repo',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.inertia-preview; format=json',
     'x-github-request-id': 'E864:7868:1408C07:19128AA:5C459A1F',
     'x-oauth-scopes':
      'admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user, write:discussion',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4981',
     'x-ratelimit-reset': '1548066974',
     'x-xss-protection': '1; mode=block' },
  request:
   { method: 'POST',
     url: 'https://api.github.com/repos/taarushv/repoName/projects',
     headers:
      { accept: 'application/vnd.github.inertia-preview+json',
        'user-agent': 'octokit.js/16.10.0 Node.js/11.6.0 (macOS High Sierra; x64)',
        authorization: 'token <my token here>',
        'content-type': 'application/json; charset=utf-8' },
     body: '{"name":"repoName"}',
     request: { validate: [Object] } },
  documentation_url:
   'https://developer.github.com/v3/projects/#create-a-repository-project' }
```

**Comment by taarushv** [comment]
No luck with curl either. 

```
{
    "message": "Not Found",
    "documentation_url": "https://developer.github.com/v3/projects/#create-a-repository-project"
}
```

**Comment by gr2m** [comment]
A 404 can often times mean that you are not authenticated correctly. Can you try another method to make sure the token is valid? For example, if you use a personal access token, try

```
const response = await octokit.request('/')
console.log(response['x-oauth-scopes'])
```

It should log sth like `public_repo`

**Comment by taarushv** [comment]
@gr2m Yeah I assumed it was a problem with auth as well (after skimming through the other similar issues). However, `console.log(response.headers['x-oauth-scopes'])` logs `delete_repo, repo`. So technically it should have permissions to create repos.

I switched the token auth for basic username/pass auth. It still throws a 404. Verified the permissions by testing other methods, which work fine.

**Comment by gr2m** [comment]
I’m sorry I don’t know what it could be. You said it didn’t work with curl either. Could you send the curl command to GitHub support? They’ll probably be more jelly to help out

**Comment by gr2m** [comment]
I don’t think it’s a problem with `@octokit/rest` so I’ll close the issue. But please keep me posted on what GitHub support says. We can of course reopen the issue if it turns out to be a bug with `@octokit/rest` after all. Thanks for your help!

**Comment by taarushv** [comment]
Hey @gr2m, GitHub support responded and it turned out to be an issue with rest.js. I was using a wrong curl command earlier. When I enter the following:

`curl https://api.github.com/user/repos -H "Authorization: token <mytokenhere>" -X POST -d '{"name": "newRepoName"}'`

It creates a new repo and returns a valid response. The node script from earlier is still returning a 404.

**Comment by gr2m** [comment]
This curl command creates a repository, the node script above creates a project

```js
Octokit.projects.createForRepo
```

Or am I missing something?
