### ISSUE TITLE
Tests seem to be failing?

### ISSUE THREAD

**Issue by davidascher** [octokit/octokit.js#122]
```
davida@suki ~/s/node-github> mocha api/v3.0.0/authorizationTest.js 

  ․․․․․

  3 passing (8s)
  2 failing

  1) [authorization] should successfully execute GET /authorizations (getAll):
     Uncaught AssertionError: 41 == 2
      at /Users/davida/src/node-github/api/v3.0.0/authorizationTest.js:48:32
      at /Users/davida/src/node-github/api/v3.0.0/authorization.js:59:17
      at IncomingMessage.<anonymous> (/Users/davida/src/node-github/index.js:752:21)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:910:16
      at process._tickCallback (node.js:415:13)

  2) [authorization] should successfully execute PATCH /authorizations/:id (update):
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runnable.js:175:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by gr2m** [comment]
This issue is very outdated so I’m going to close it :) We are working on bringing back tests as part of the transition to the @octokit org: https://github.com/octokit/discussions/issues/7
