### ISSUE TITLE
addLabels issue_number doesn't work

### ISSUE THREAD

**Issue by hipstersmoothie** [octokit/octokit.js#1333]
In the following code

```ts
    const result = await this.ghub.issues.addLabels({
      // Type definitions do not seem to match
      // issue_number: pr,
      number: pr,
      owner: this.options.owner,
      repo: this.options.repo,
      labels: [label]
    });
```

when i try to use `issue_number` i get the following error. on v16.24.1 of octokit/rest

```
{ HttpError: Empty value for parameter 'number': undefined
    at values.forEach (/home/circleci/auto/node_modules/@octokit/rest/plugins/validate/validate.js:89:15)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.parameterName (/home/circleci/auto/node_modules/@octokit/rest/plugins/validate/validate.js:63:12)
    at Array.forEach (<anonymous>)
    at validate (/home/circleci/auto/node_modules/@octokit/rest/plugins/validate/validate.js:40:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'HttpError',
  status: 400,
  headers: null,
  request: 
   { method: 'POST',
     baseUrl: 'https://api.github.com',
     headers: 
      { accept: 'application/vnd.github.v3+json',
        'user-agent': 'octokit.js/16.24.1 Node.js/8.14.1 (Linux 4.4; x64)' },
     mediaType: { format: '', previews: [Array] },
     request: { validate: [Object] },
     url: '/repos/:owner/:repo/issues/:number/labels',
     issue_number: 327,
     owner: 'intuit',
     repo: 'auto',
     labels: [ 'released' ],
     data: [ 'released' ] } }
```

**Comment by gr2m** [comment]
I’m sorry, but I was not able to reproduce the problem.

```js
const octokit = require('@octokit/rest')()

const nock = require('nock')
  nock('https://api.github.com')
    .post('/repos/owner/repo/issues/123/labels')
    .reply(200, {
      ok: true
    })
    .persist()

octokit.issues.addLabels({
  number: 123,
  owner: 'owner',
  repo: 'repo',
  labels: ['label']
})
  .then(response => {
    console.log('with "number": ', response.data)
  })

octokit.issues.addLabels({
  issue_number: 123,
  owner: 'owner',
  repo: 'repo',
  labels: ['label']
})
  .then(response => {
    console.log('with "issue_number": ', response.data)
  })

// logs deprecation message for "number" parameter and
// with "number":  { ok: true }
// with "issue_number":  { ok: true }
```

Where does `this.ghub` come from?

The Error you see

> Empty value for parameter 'number': undefined

would occur with a version smaller than `v16.24.1`. Please check with `npm ls`

**Comment by gr2m** [comment]
This should be resolve now, make sure to update to latest @octokit/rest
