### ISSUE TITLE
updateBranchProtection requires luke-cage preview

### ISSUE THREAD

**Issue by joepagan** [octokit/octokit.js#1368]
Got an identical issue to this but when trying to run `updateBranchProtection`:
https://github.com/octokit/routes/issues/356

The docs suggest I do not need to pass a mediaType:
https://octokit.github.io/rest.js/#octokit-routes-repos-update-branch-protection

However, running:
```js
const response = await octokit.repos.updateBranchProtection({
    owner,
    repo,
    branch: 'dev',
    required_status_checks: {
      strict: true,
      contexts: [],
    },
    enforce_admins: true,
    required_pull_request_reviews: {
      dismiss_stale_reviews: true,
      required_approving_review_count: 1,
    },
    restrictions: {
      users: [],
      teams: [],
    },
  }).catch((err) => console.error(err));
```

Results in the following error response:
```bash
{ HttpError: If you would like to help us test the Require Multiple Reviewers API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.
    at response.text.then.message (/Users/joe/var/www/repo/node_modules/@octokit/request/lib/request.js:56:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  status: 415,
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
     connection: 'close',
     'content-length': '303',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Thu, 16 May 2019 10:58:18 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '415 Unsupported Media Type',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'FA40:3A20:9B6F9C:14F2BB9:5CDD424A',
     'x-oauth-scopes': 'admin:org, repo',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4993',
     'x-ratelimit-reset': '1558007898',
     'x-xss-protection': '1; mode=block' },
  request:
   { method: 'PUT',
     url:
      'https://api.github.com/repos/org/repo/branches/dev/protection',
     headers:
      { accept: 'application/vnd.github.v3+json',
        'user-agent':
         'User agent octokit.js/16.25.2 Node.js/10.14.2 (macOS Mojave; x64)',
        authorization: 'token [REDACTED]',
        'content-type': 'application/json; charset=utf-8' },
     body:
      '{"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":true,"required_pull_request_reviews":{"dismiss_stale_reviews":true,"required_approving_review_count":1},"restrictions":{"users":[],"teams":[]}}',
     request: { validate: [Object] } },
  documentation_url:
   'https://developer.github.com/v3/repos/branches/#update-branch-protection' }
```

Adding the following resolves the issue:
```js
    mediaType: {
      previews: [
        'luke-cage',
      ],
    },
```

**Comment by gr2m** [comment]
This is great, thank you for reporting the issue.

It will need to be resolved in octokit/routes though, as the endpoint methods are fully generated based on it, included the setting of required preview headers.

Could you file an issue there, similar to https://github.com/octokit/routes/issues/356?

**Comment by gr2m** [comment]
Here is the endpoint documentation: https://developer.github.com/v3/repos/branches/#update-branch-protection

Here is the JSON that `octokit/routes` is parsing it into, the preview is flagged as not required: 
https://github.com/octokit/routes/blob/939feb18a5f7a2bd098ee67180e946430bdfb301/routes/api.github.com/repos/update-branch-protection.json#L11

> To access the API during the preview period, you must provide a custom [media type](https://developer.github.com/v3/media) in the `Accept` header

That sentence should make `octokit/routes` flag the preview as required. Looks like a bug to me

**Comment by joepagan** [comment]
Sorry a premautre close, it appears that despite this being resolved here: https://github.com/octokit/routes/issues/412

It is not resolved here. I have just tried this and got the following response:

```
🐙 github.branchProtection for master
{ HttpError: If you would like to help us test the Require Multiple Reviewers API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.
    at response.text.then.message (/Users/joe/var/www/beanstalk-migration/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  status: 415,
  headers:
```

Let me know if you need a full response object as I'll have to redact a few things.

**Comment by gr2m** [comment]
It would be good if you could share the `request: { headers: {...} }` part from the logged error object

**Comment by joepagan** [comment]
Hey @gr2m here you go:

```bash
{ HttpError: If you would like to help us test the Require Multiple Reviewers API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.
    at response.text.then.message (/Users/joe/var/www/migration/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  status: 415,
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
     connection: 'close',
     'content-length': '303',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Thu, 05 Sep 2019 11:44:25 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '415 Unsupported Media Type',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'F72A:33B3E:8A40B3:A70E7F:5D70F519',
     'x-oauth-scopes': 'admin:org, repo',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4953',
     'x-ratelimit-reset': '1567687440',
     'x-xss-protection': '1; mode=block' },
  request:
   { method: 'PUT',
     url:
      'https://api.github.com/repos/org/tester.com7/branches/master/protection',
     headers:
      { accept: 'application/vnd.github.v3+json',
        'user-agent':
         'Extreme Beanstalk Migration octokit.js/16.28.7 Node.js/10.16.3 (macOS Mojave; x64)',
        authorization: 'token [REDACTED]',
        'content-type': 'application/json; charset=utf-8' },
     body:
      '{"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":false,"required_pull_request_reviews":{"dismiss_stale_reviews":true,"required_approving_review_count":1},"restrictions":{"users":[],"teams":[]}}',
     request:
      { hook: [Function: bound bound register], validate: [Object] } },
  documentation_url:
   'https://developer.github.com/v3/repos/branches/#update-branch-protection' }
```

**Comment by gr2m** [comment]
The endpoint does in fact not require the `luke-cage` preview, it is an optional preview that you can set to use additional features such as requiring a specific number of reviews:

https://developer.github.com/v3/repos/branches/#update-branch-protection

So it's actually working as intended

**Comment by joepagan** [comment]
Ah crap sorry didn't realise, sorry for the noise! That's what I was trying to do.

**Comment by gr2m** [comment]
No problem at all, I understand how this is confusing, our docs should list the optional preview headers to make that clear, we are aware of that

**Comment by saurabhtalreja** [comment]
I was trying to implement create protection API in my java code on branch using "required_pull_request_reviews"-->"required_approving_review_count" : 1
I faced the same error of 415 as @joepagan , and it worked fine when I injected header "Accept" :"application/vnd.github.luke-cage-preview+json"
But the strange thing is even without using Accept Header in Postman it works fine...Don't know the reason.. @gr2m can you shed some light on this.
