### ISSUE TITLE
activity.listReceivedEventsForUser and activity.getEventsForUser return 404

### ISSUE THREAD

**Issue by channg** [octokit/octokit.js#1551]
```
activity.activity.getEventsForUser({userName:'golang'}) return 404

activity.listReceivedEventsForUser({userName:'golang'})return 404


```

https://api.github.com/users/golang/events

https://api.github.com/users/golang/received_events/public
is ok

**Comment by gr2m** [comment]
I'm sorry I missed your issue. 

There is a `octokit.activity.listReceivedEventsForUser()` function, but the parameter is `username`, not `userName`. 

There is no `octokit.activity.getEventsForUser()` method.

**Comment by gr2m** [comment]
I'm closing the issue, but please continue to ask follow up questions if you have any

**Comment by channg** [comment]
@gr2m 
```
octokit.activity.listReceivedEventsForUser({username:'golang'}) 
```
return

```
HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received"}
    at /Users/xuezhiwen/goo/node_modules/@octokit/rest/lib/request/request.js:72:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xuezhiwen/goo/service/users.js:65:23 {
  name: 'HttpError',
  code: 404,
  status: 'Not Found',
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 15 Feb 2020 11:11:48 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': '',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; param=star; format=json',
    'x-github-request-id': 'D01A:47FA:70A74:F18B6:5E47D1F4',
    'x-oauth-client-id': '583c0bd97cf17d49df2d',
    'x-oauth-scopes': '',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4160',
    'x-ratelimit-reset': '1581767218',
    'x-xss-protection': '1; mode=block'
  }
}

```

but

https://api.github.com/users/golang/events

https://api.github.com/users/golang/received_events/public
is ok

**Comment by gr2m** [comment]
Can you log the `error.request` property?

```js
octokit.activity.listReceivedEventsForUser({username:'golang'})
  .catch(error => console.error(error.request)
```
