### ISSUE TITLE
Deno: `deno run` does not exit

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#2079]
Follow up to https://github.com/octokit/octokit.js/issues/2075

**What happened?**

@laughedelic was able to [narrow down the problem to the throttle plugin](https://github.com/octokit/octokit.js/issues/2075#issuecomment-822076111).

> ```ts
> import { Octokit } from "https://cdn.skypack.dev/@octokit/core";
> import { throttling } from "https://cdn.skypack.dev/@octokit/plugin-throttling";
> const MyOctokit = Octokit.plugin(throttling);
> const octokit = new MyOctokit({
>   auth: Deno.env.get("GITHUB_TOKEN"),
>   throttle: {
>     onRateLimit: (retryAfter: any, options: any, octokit: any) => {
>       return true;
>     },
>     onAbuseLimit: (retryAfter: any, options: any, octokit: any) => {
>       octokit.log.warn(`Abuse detected for request ${options.method} ${options.url}`);
>     },
>   },
> });
> 
> octokit.log.warn("foo");
> ```
> 
> It prints `foo` and hangs. If I remove everything related `throttling`, it prints the message and exits.
> 
> A workaround for this hanging is to add `Deno.exit(0)` at the end.

**What did you expect to happen?**

The deno process should exit, just like Node does

**What the problem might be**

The throttle plugin is using [bottleneck](https://github.com/SGrondin/bottleneck) by @SGrondin. Maybe it's a known issue?

I'd appreciate if someone with more deno experience could try to reproduce the hanging problem with just Bottleneck. The sourcecode where we use `bottleneck` is here: https://github.com/octokit/plugin-throttling.js/

**Comment by wperron** [comment]
Hey, Deno maintainer here :wave: I was actually just trying to use octokit to extract our release download stats and hit this issue. So far my script is as simple as it gets :
```typescript
const octokit = new Octokit({ auth: Deno.env.get("GITHUB_TOKEN") });
const repo = await octokit.rest.repos.get({
  owner: "denoland",
  repo: "deno",
});
```

I also traced it down to plugin-throttling, I'll try to get a minimal repro with just Bottleneck next week. Don't hesitate to contact me too if you happen to be working on it.

**Comment by gr2m** [comment]
thank you so much @wperron for looking into it! Please let me know if there is anything that I can help with

**Comment by wperron** [comment]
I believe I found the reason for the hang, probably around the `_startAutoCleanup` function in Bottleneck ([here](https://github.com/SGrondin/bottleneck/blob/master/light.js#L919)).

In Deno, just like in the browser `setInterval` [returns an IntervalID](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#return_value) as opposed to the [`Timeout` object](https://nodejs.org/dist/latest-v16.x/docs/api/timers.html#timers_class_timeout) returned by Node.js's `setInterval`. I have made the following little script to highlight the differences in Node.js and Deno

```javascript
// Nodejs: `node this.js`
// Deno: `deno run this.js`
const base = setInterval(() => {}, 1);
if (typeof base.unref === "function") {
  base.unref();
} else {
  console.log("can't unref");
}
```

Without using the `unref` they both hang forever. `unref` allows Node to exit when it reaches the end of the script, regardless of the interval running in the background. I have a suspicion that the hang is also present when using octokit directly in the browser as an ES Module, but that due to the nature of how browsers work, it's simply not being noticed. I'm having issues with Skypack at the moment so Octokit simply won't load. I'll try again soon and confirm whether or not my hypothesis is correct.

**Comment by fixbullshit14** [comment]
hi pls help me 
i have no idea 

{"crashreporter_key":"43cd7e99167b919a3a11347cf6ecf9d47f733c14","bug_type":"211","timestamp":"2022-08-05 07:00:58.00 +0700","os_version":"iPhone OS 15.5 (19F77)","incident_id":"CF2E895A-09E5-4EB6-9A65-D4BF657E9960"}
{"_marker":"<metadata>","_preferredUserInterfaceLanguage":"id-ID","_userInterfaceLanguage":"id","_userSetRegionFormat":"ID","basebandChipset":"mav21","basebandFirmwareVersion":"","configParentUuid":"029a70d8-e2e0-48dd-8bae-c9b7a097de45","configUuid":"a84987e4-f373-42b4-a2d7-735b24924a8e","currentCountry":"<unknown>","deviceCapacity":128,"homeCarrierCountry":"<unknown>","homeCarrierName":"<unknown>","isDualSim":false,"rolloverReason":"scheduled","servingCarrierName":"<unknown>","startTimestamp":"2022-08-04T00:00:01Z","trialExperiments":"0","trialRollouts":"0","version":"2.3"}
{"message":{"BogusFieldNotActuallyEverUsed":null,"Count":4,"daily_total_BogusMeasureNotActuallyEverUsed":null},"name":"StabilityHeartBeatCount5","sampling":100,"uuid":"3c8f638f-d492-465e-9e27-546a163beac9_2"}
{"_marker":"<end-of-file>"}

**Comment by st3fan** [comment]
@wperron I'm still running into this today. As a workaround I'm ending my program with a `Deno.exit(0)` now but I was wondering if there is anything I could do or contribute to avoid that. Any ideas?

**Comment by michielbdejong** [comment]
Hey @gr2m nice to see you here! :) I'm also running into this issue; maybe the use of `deno test` helps us to trace it:
* Save this as `test.ts`:
```ts
import { Octokit } from "https://esm.sh/octokit@4.0.2?dts";
Deno.test("hello", async () => {
  const octokit = new Octokit({ auth: Deno.env.get("GITHUB_TOKEN") });
  await octokit.rest.repos.get({
    owner: "denoland",
    repo: "deno",
  });
});
```
* Run:
```sh
$ deno test -A --trace-leaks test.ts
Check file:///Users/michiel/test.ts
running 1 test from ./test.ts
hello ... FAILED (373ms)

 ERRORS 

hello => ./test.ts:2:6
error: Leaks detected:
  - An interval was started in this test, but never completed. This is often caused by not calling `clearInterval`. The operation was started here:
    at Object.queueUserTimer (ext:core/01_core.js:738:9)
    at setInterval (ext:deno_web/02_timers.js:83:15)
    at u._startAutoCleanup (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:14348)
    at new u (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:12962)
    at j (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:1925)
    at Array._ (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:2397)
    at new h (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:1840)
    at new <anonymous> (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:692)
    at file:///Users/michiel/test.ts:3:19
    at innerWrapped (ext:cli/40_test.js:174:11)
  - An interval was started in this test, but never completed. This is often caused by not calling `clearInterval`. The operation was started here:
    at Object.queueUserTimer (ext:core/01_core.js:738:9)
    at setInterval (ext:deno_web/02_timers.js:83:15)
    at u._startAutoCleanup (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:14348)
    at new u (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:12962)
    at j (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:1991)
    at Array._ (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:2397)
    at new h (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:1840)
    at new <anonymous> (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:692)
    at file:///Users/michiel/test.ts:3:19
    at innerWrapped (ext:cli/40_test.js:174:11)
  - An interval was started in this test, but never completed. This is often caused by not calling `clearInterval`. The operation was started here:
    at Object.queueUserTimer (ext:core/01_core.js:738:9)
    at setInterval (ext:deno_web/02_timers.js:83:15)
    at u._startAutoCleanup (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:14348)
    at new u (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:12962)
    at j (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:2067)
    at Array._ (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:2397)
    at new h (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:1840)
    at new <anonymous> (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:692)
    at file:///Users/michiel/test.ts:3:19
    at innerWrapped (ext:cli/40_test.js:174:11)
  - An interval was started in this test, but never completed. This is often caused by not calling `clearInterval`. The operation was started here:
    at Object.queueUserTimer (ext:core/01_core.js:738:9)
    at setInterval (ext:deno_web/02_timers.js:83:15)
    at u._startAutoCleanup (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:14348)
    at new u (https://esm.sh/v135/bottleneck@2.19.5/denonext/light.js:3:12962)
    at j (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:2150)
    at Array._ (https://esm.sh/v135/@octokit/plugin-throttling@9.3.0/denonext/plugin-throttling.mjs:2:2397)
    at new h (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:1840)
    at new <anonymous> (https://esm.sh/v135/@octokit/core@6.1.2/denonext/core.mjs:2:692)
    at file:///Users/michiel/test.ts:3:19
    at innerWrapped (ext:cli/40_test.js:174:11)

 FAILURES 

hello => ./test.ts:2:6

FAILED | 0 passed | 1 failed (377ms)

error: Test failed
```

It should probably be possible to extract a minimal snippet of code from [plugin-throttling.js](https://github.com/octokit/plugin-throttling.js/blob/main/src/wrap-request.ts) that calls [Bottleneck](https://www.npmjs.com/package/bottleneck) and shows this problem.

**Comment by michielbdejong** [comment]
Got it; opened an upstream issue: https://github.com/SGrondin/bottleneck/issues/225

**Comment by wolfy1339** [comment]
The bottleneck package hasn't seen any new commits in the last 4 years.

At this point, it's best to find a new library that doesn't have their problem.

**Comment by milags** [comment]
Wanted to chime in here as there is a difference in behavior depending on whether you import from `esm.sh` or `npm`. I will post 2 examples, with the only difference being the import source.

Both examples are executed as follows with `deno v2.2.2`: 

```
GITHUB_TOKEN=$(gh auth token) deno -E main.ts
```

- Importing from `https://esm.sh/octokit?dts`, as recommended:
```
import { Octokit } from "https://esm.sh/octokit?dts"

const GITHUB_TOKEN = Deno.env.get("GITHUB_TOKEN");

const octokit = new Octokit({
	auth: GITHUB_TOKEN,
});
```
Without even making a request, simply initializing the `Octokit` instance causes the process to not exit.


- Adding a dependency on `npm:octokit` and using the npm package instead:
```
import { Octokit } from "npm:octokit"

const GITHUB_TOKEN = Deno.env.get("GITHUB_TOKEN");

const octokit = new Octokit({
	auth: GITHUB_TOKEN,
});
```
The process exits as expected.


I'm not really sure what the implication here is, but is there a difference between how `Octokit.js` is packaged for `npm` vs `esm.sh`?

**Comment by wperron** [comment]
This issue was opened almost 4 years ago at this point, way before any sort of npm support was on the radar for Deno. Now I would expect it to work out of the box with Deno 2 importing from `npm:octokit`, and if that's not the case, it's probably an issue with Deno's npm compat.

**Comment by milags** [comment]
@wperron yes, I'm aware. I guess what confuses me is why it works importing from `npm:octokit` but not `https://esm.sh/octokit?dts`? Earlier in the thread, it was suggested that this may come down to a difference in behavior between `deno` and `node` themselves, but these are both being run with `deno`.

**Comment by wolfy1339** [comment]
Try with the following in your `deno.json`, it works for me locally
```json
{
  "imports": {
    "octokit": "https://esm.sh/*octokit@4.1.2?target=denonext"
  },
  "scopes": {
    "https://esm.sh/": {
      "@octokit/app": "https://esm.sh/@octokit/app@15.1.5?target=denonext",
      "@octokit/auth-app": "https://esm.sh/@octokit/auth-app@7.1.5?target=denonext",
      "@octokit/auth-unauthenticated": "https://esm.sh/@octokit/auth-unauthenticated@6.1.2?target=denonext",
      "@octokit/core/types": "https://esm.sh/@octokit/core@6.1.4/dist-types/types.d.ts?target=denonext",
      "@octokit/core": "https://esm.sh/@octokit/core@6.1.4?target=denonext",
      "@octokit/oauth-app": "https://esm.sh/@octokit/oauth-app@7.1.6?target=denonext",
      "@octokit/plugin-paginate-graphql": "https://esm.sh/@octokit/plugin-paginate-graphql@5.2.4?target=denonext&deps=@octokit/core@6.1.3",
      "@octokit/plugin-paginate-rest": "https://esm.sh/@octokit/plugin-paginate-rest@11.4.3?target=denonext",
      "@octokit/plugin-rest-endpoint-methods": "https://esm.sh/@octokit/plugin-rest-endpoint-methods@13.3.1?target=denonext",
      "@octokit/plugin-retry": "https://esm.sh/@octokit/plugin-retry@7.1.3?target=denonext",
      "@octokit/plugin-throttling": "https://esm.sh/@octokit/plugin-throttling@9.4.0?target=denonext",
      "@octokit/request-error": "https://esm.sh/@octokit/request-error@6.1.7?target=denonext",
      "@octokit/types": "https://esm.sh/@octokit/types@13.8.0?target=denonext",
      "@octokit/webhooks": "https://esm.sh/@octokit/webhooks@13.7.4?target=denonext"
    }
  }
```

**Comment by wolfy1339** [comment]
That would probably be a bug in how esm.sh repackages some of the dependencies, given that giving the explicit `denonext` target, and using the `npm:` specifier work just fine.

I think the action item here, is to update all the README across the @octokit organization to add an explicit Deno entryrecommending the `npm:` specifier or replace esm.sh depending on the package as some aren't meant for browser usage
