### ISSUE TITLE
Won't compile in TypeScript

### ISSUE THREAD

**Issue by jdgarcia** [octokit/octokit.js#2131]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQTGOBfOAzKERwDkEAxjBANbAyEDcAUPSRAHYDO8A5tQBYCuAI1ToAvHBYBTAO4o0ACgT04cAIZoAkgBMAXHACMAJgDMAGiVwwUYADcVMCQGkJAT12FC9DAEoG9CQA9IWDhNCWwVPgAbLl5BYQYgA

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [ ] Deno

### Version

```
npm ERR! peer dep missing: graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0, required by graphql-iso-date@3.6.1
├── @octokit/openapi-types@8.3.0
├─┬ octokit@1.1.0
│ ├─┬ @octokit/app@12.0.3
│ │ ├─┬ @octokit/auth-app@3.5.3
│ │ ├─┬ @octokit/auth-unauthenticated@2.1.0
│ │ └─┬ @octokit/webhooks@9.10.0
│ │   ├── @octokit/webhooks-methods@2.0.0
│ │   ├── @octokit/webhooks-types@4.1.0
│ ├─┬ @octokit/core@3.5.1
│ │ ├─┬ @octokit/auth-token@2.4.5
│ │ ├─┬ @octokit/graphql@4.6.4
│ │ ├─┬ @octokit/request@5.6.0
│ │ │ ├─┬ @octokit/endpoint@6.0.12
│ │ ├─┬ @octokit/request-error@2.1.0
│ ├─┬ @octokit/oauth-app@3.4.0
│ │ ├─┬ @octokit/auth-oauth-app@4.3.0
│ │ │ ├─┬ @octokit/auth-oauth-device@3.1.2
│ │ ├─┬ @octokit/auth-oauth-user@1.3.0
│ │ ├── @octokit/oauth-authorization-url@4.3.2
│ │ ├─┬ @octokit/oauth-methods@1.2.4
│ ├─┬ @octokit/plugin-paginate-rest@2.14.0
│ ├─┬ @octokit/plugin-rest-endpoint-methods@5.4.1
│ ├─┬ @octokit/plugin-retry@3.0.9
│ ├─┬ @octokit/plugin-throttling@3.5.1
│ └─┬ @octokit/types@6.19.0
```

### What happened?

I added the `octokit` package to my project. As soon as I reference it in code, the TypeScript compilation fails.

Here is the compilation output with sensitive folder names replaced:
```
[22:04:29] Starting 'compile'...
PATH_TO_PROJECT/node_modules/@octokit/plugin-paginate-rest/dist-types/types.d.ts(23,53): error TS2536: Type '"data"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(7,17): error TS2536: Type '"parameters"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(7,35): error TS2536: Type '"parameters"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(8,9): error TS2536: Type '"parameters"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(9,94): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(9,146): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(9,146): error TS2536: Type '"content"' cannot be used to index type 'T["requestBody"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(9,176): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(9,176): error TS2536: Type '"content"' cannot be used to index type 'T["requestBody"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(9,176): error TS2536: Type '"application/json"' cannot be used to index type 'T["requestBody"]["content"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(11,21): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(11,21): error TS2536: Type '"content"' cannot be used to index type 'T["requestBody"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(11,51): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(11,51): error TS2536: Type '"content"' cannot be used to index type 'T["requestBody"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(12,13): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(12,13): error TS2536: Type '"content"' cannot be used to index type 'T["requestBody"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(13,38): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(13,57): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(13,57): error TS2536: Type '"application/json"' cannot be used to index type 'T["requestBody"]'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(15,21): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(15,40): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(16,13): error TS2536: Type '"requestBody"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(54,79): error TS2536: Type '"content"' cannot be used to index type 'T'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(58,96): error TS2536: Type '"responses"' cannot be used to index type 'R'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(58,153): error TS2536: Type '"responses"' cannot be used to index type 'R'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(58,207): error TS2536: Type '"responses"' cannot be used to index type 'R'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(58,250): error TS2536: Type '"responses"' cannot be used to index type 'R'.
PATH_TO_PROJECT/node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(58,292): error TS2536: Type '"responses"' cannot be used to index type 'R'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,13): error TS1005: '=' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,15): error TS2304: Cannot find name 'EmitterWebhookEvent'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,15): error TS2695: Left side of comma operator is unused and has no side effects.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,15): error TS2695: Left side of comma operator is unused and has no side effects.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,15): error TS2695: Left side of comma operator is unused and has no side effects.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,15): error TS2695: Left side of comma operator is unused and has no side effects.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,36): error TS2304: Cannot find name 'EmitterWebhookEventName'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,61): error TS2304: Cannot find name 'HandlerFunction'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,78): error TS2552: Cannot find name 'Options'. Did you mean 'Option'?
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,87): error TS2304: Cannot find name 'WebhookEventHandlerError'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,114): error TS2304: Cannot find name 'from'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(1,119): error TS1005: ';' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(3,18): error TS2304: Cannot find name 'EmitterWebhookEventName'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(3,69): error TS2304: Cannot find name 'HandlerFunction'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(4,28): error TS2304: Cannot find name 'EmitterWebhookEvent'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(5,30): error TS2304: Cannot find name 'WebhookEventHandlerError'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(6,30): error TS2304: Cannot find name 'EmitterWebhookEventName'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(6,81): error TS2304: Cannot find name 'HandlerFunction'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(7,20): error TS2304: Cannot find name 'EmitterWebhookEvent'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/event-handler/index.d.ts(9,67): error TS2304: Cannot find name 'Options'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/index.d.ts(2,56): error TS2305: Module '"../../../../../../../../..PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types"' has no exported member 'HandlerFunction'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/index.d.ts(2,73): error TS2305: Module '"../../../../../../../../..PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types"' has no exported member 'Options'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/index.d.ts(2,82): error TS2305: Module '"../../../../../../../../..PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types"' has no exported member 'WebhookError'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/index.d.ts(2,96): error TS2305: Module '"../../../../../../../../..PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types"' has no exported member 'WebhookEventHandlerError'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/index.d.ts(2,122): error TS2305: Module '"../../../../../../../../..PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types"' has no exported member 'EmitterWebhookEventWithStringPayloadAndSignature'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/index.d.ts(2,172): error TS2305: Module '"../../../../../../../../..PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types"' has no exported member 'EmitterWebhookEventWithSignature'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,8): error TS2300: Duplicate identifier 'type'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,13): error TS1005: '=' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,15): error TS2304: Cannot find name 'WebhookEventMap'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,15): error TS2695: Left side of comma operator is unused and has no side effects.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,32): error TS2304: Cannot find name 'WebhookEventName'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,51): error TS2304: Cannot find name 'from'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(2,56): error TS1005: ';' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(4,8): error TS2300: Duplicate identifier 'type'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(4,13): error TS1005: '=' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(4,15): error TS2304: Cannot find name 'emitterEventNames'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(4,35): error TS2304: Cannot find name 'from'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(4,40): error TS1005: ';' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(5,54): error TS2304: Cannot find name 'emitterEventNames'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,138): error TS1110: Type expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,141): error TS2304: Cannot find name 'infer'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,147): error TS1005: '}' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,147): error TS2304: Cannot find name 'TWebhookEvent'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,160): error TS1128: Declaration or statement expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,161): error TS1128: Declaration or statement expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,162): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,163): error TS1005: ';' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,164): error TS2304: Cannot find name 'infer'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,170): error TS1005: ';' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(6,170): error TS2304: Cannot find name 'TAction'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(41,55): error TS1005: ';' expected.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(41,55): error TS2304: Cannot find name 'octokit'.
PATH_TO_PROJECT/node_modules/@octokit/webhooks/dist-types/types.d.ts(62,1): error TS1160: Unterminated template literal.
TypeScript: 14 syntax errors
TypeScript: 67 semantic errors
TypeScript: emit succeeded (with errors)
[22:04:41] 'compile' errored after 11 s
[22:04:41] Error: TypeScript: Compilation failed
    at Output.mightFinish (PATH_TO_PROJECT/node_modules/gulp-typescript/release/output.js:130:43)
    at PATH_TO_PROJECT/node_modules/gulp-typescript/release/output.js:43:22
[22:04:41] 'building' errored after 11 s
[22:04:41] 'build' errored after 11 s
error Command failed with exit code 1.
```

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by jdgarcia** [comment]
Ok, I think I figured out why, it's because all those packages use Typescript 4 features while our project is still using Typescript 3.5.
