### ISSUE TITLE
[BUG]: Breaks on Vite dep prebuild

### ISSUE THREAD

**Issue by Ddupasquier** [octokit/octokit.js#2404]
### What happened?

In my Svelte application, when I install octokit and attempt to use it server side (+page.ts) I get the error displayed in the logs below.
I have tried deleting my package.lock and node_modules and reinstalling, but to no avail.
My assumption is that this is a compatibility issue between Vite and Octokit, but I don't how I would debug this so I figured I'd ask a pro.

#Reproduction Steps

This is the link to the repo:
https://github.com/Ddupasquier/portfolio_3.0/tree/octokit

Fork (OR spin up your own new svelte project)
npm i
npm run dev
Check terminal
Fault Type

Permanent - Occurring repeatably

#Blocking?

Yes

### Versions

Vite 3.1
octokit 2.0.14

### Relevant log output

```shell
[plugin vite:dep-pre-bundle] Failed to resolve entry for package "@octokit/plugin-retry". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1327:21:
      1327 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34841:11)
    at resolvePackageEntry (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34838:5)
    at tryNodeResolve (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34584:20)
    at Context.resolveId (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34357:28)
    at Object.resolveId (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:41039:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63173:21
    at async file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:35110:34
    at async requestCallbacks.on-resolve (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1327:22)
    at async handleRequest (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:697:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1251:20:
      1251 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:35090:19)
    at handlePlugins (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1251:21)
    at buildOrServeImpl (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:942:5)
    at Object.buildOrServe (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:750:5)
    at /home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:2085:17
    at new Promise (<anonymous>)
    at Object.build (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:2084:14)
    at build (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1931:51)
    at runOptimizeDeps (file:///home/ddupasquier/portfolio_3.0/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:42368:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/octokit/dist-web/index.js:4:22:
      4 │ import { retry } from '@octokit/plugin-retry';
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~

2:06:38 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1327:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@octokit/plugin-retry". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1566:15)
    at /home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1024:28
    at runOnEndCallbacks (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1438:61)
    at buildResponseToResult (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1022:7)
    at /home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/ddupasquier/portfolio_3.0/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is a known issue https://github.com/octokit/plugin-retry.js/issues/405
