### ISSUE TITLE
[BUG]: CJS Loader "Unexpected token '{'"

### ISSUE THREAD

**Issue by maka-io** [octokit/octokit.js#2663]
### What happened?

In a MeteorJS environment, adding `import { Octokit } from 'octokit'` results in immediate crash.

### Versions

Octokit v3.2.0
Node v. 14.21.4

### Relevant log output

```shell
app/node_modules/@octokit/core/dist-node/index.js:42
W20240425-13:36:58.188(-4)? (STDERR)   static {
W20240425-13:36:58.188(-4)? (STDERR)          ^
W20240425-13:36:58.188(-4)? (STDERR) 
W20240425-13:36:58.188(-4)? (STDERR) SyntaxError: Unexpected token '{'
W20240425-13:36:58.188(-4)? (STDERR)     at wrapSafe (internal/modules/cjs/loader.js:1031:16)
W20240425-13:36:58.189(-4)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1080:27)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
~~You have to use ESM and~~ we target ES2022.

We require NodeJS v18+

**Comment by wolfy1339** [comment]
As per the Meteor docs,

> Meteor 2.x runs on a deprecated Node.js version (14). Meteor 3.0, currently in its Release Candidate version, runs on Node.js v20. For more information, please consult our [migration guide](https://guide.meteor.com/3.0-migration.html).

We support the 2 latest LTS releases, and provide support for the latest release.

The version we require is documented in our `package.json` and our build scripts

**Comment by nicu-chiciuc** [comment]
It also doesn't work for Meteor 3.3.1  which uses node v22.18.0, albeit the error is different:

```sh
meteor
[[[[[ ~/dev/my/lumina/apps/meteor_lumina ]]]]]

=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
=> Linted your app. No linting errors.        
W20250810-18:41:03.194(3)? (STDERR) packages/core-runtime.js:189
W20250810-18:41:03.200(3)? (STDERR)             throw error;
W20250810-18:41:03.200(3)? (STDERR)             ^
W20250810-18:41:03.200(3)? (STDERR) 
W20250810-18:41:03.200(3)? (STDERR) Error: Cannot find module '@octokit/rest'
W20250810-18:41:03.200(3)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20250810-18:41:03.200(3)? (STDERR)     at Module.require (packages/modules-runtime.js:240:17)
W20250810-18:41:03.200(3)? (STDERR)     at Module.mod.require (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20250810-18:41:03.200(3)? (STDERR)     at Module.moduleLink [as link] (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
W20250810-18:41:03.200(3)? (STDERR)     at module.wrapAsync.self (/Users/nicu/dev/my/lumina/apps/meteor_lumina/.meteor/local/build/programs/server/app/app.js:45:359)
W20250810-18:41:03.200(3)? (STDERR)     at Module.wrapAsync (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:252:8)
W20250810-18:41:03.201(3)? (STDERR)     at module (/Users/nicu/dev/my/lumina/apps/meteor_lumina/.meteor/local/build/programs/server/app/app.js:45:9)
W20250810-18:41:03.201(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20250810-18:41:03.201(3)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20250810-18:41:03.201(3)? (STDERR)     at Module.mod.require (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20250810-18:41:03.201(3)? (STDERR)     at Module.moduleLink [as link] (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
W20250810-18:41:03.201(3)? (STDERR)     at module.wrapAsync.self (/Users/nicu/dev/my/lumina/apps/meteor_lumina/.meteor/local/build/programs/server/app/app.js:168:578)
W20250810-18:41:03.201(3)? (STDERR)     at Module.wrapAsync (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:252:8)
W20250810-18:41:03.201(3)? (STDERR)     at module (/Users/nicu/dev/my/lumina/apps/meteor_lumina/.meteor/local/build/programs/server/app/app.js:168:9)
W20250810-18:41:03.201(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20250810-18:41:03.201(3)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20250810-18:41:03.201(3)? (STDERR) 
W20250810-18:41:03.201(3)? (STDERR) Node.js v22.18.0
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

I've also tried using dynamic imports but then it also fails:
```sh
W20250810-18:41:53.923(3)? (STDERR) Error fetching GitHub repositories: Error: Cannot find module '@octokit/rest'
W20250810-18:41:53.923(3)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20250810-18:41:53.923(3)? (STDERR)     at Module.require (packages/modules-runtime.js:240:17)
W20250810-18:41:53.923(3)? (STDERR)     at Module.mod.require (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20250810-18:41:53.924(3)? (STDERR)     at Module.moduleLink [as link] (/Users/nicu/.meteor/packages/modules/.0.20.3.k6ys3v8i1mk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
W20250810-18:41:53.924(3)? (STDERR)     at getNamespace (packages/dynamic-import.js:629:10)
W20250810-18:41:53.924(3)? (STDERR)     at packages/dynamic-import.js:464:12
W20250810-18:41:53.924(3)? (STDERR)     at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

So

**Comment by wolfy1339** [comment]
Please create a new issue with a reproducible example of the issue.

It's module resolution that seems to be broken

**Comment by wolfy1339** [comment]
@nicu-chiciuc Meteor doesn't support the `exports` field yet.
https://github.com/meteor/meteor/pull/13520

You need ESM, compatibility with the `exports` field and Node 20+

Even though it says it uses Node 22, it still isn't fully compatible with modern ESM modules
