### ISSUE TITLE
[BUG]: types don't resolve for `@octokit/core` on esm.sh

### ISSUE THREAD

**Issue by thisguycodes** [octokit/octokit.js#2762]
### What happened?

`deno check ...` consistently errors when using octokit via esm.sh

### Versions

Octokit.js v4.0.2
Deno v2.0.6

### Relevant log output

```shell
$ deno check *.ts **/*.ts --allow-import
error: Failed resolving types. Relative import path "@octokit/core/types" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/octokit@4.0.2/X-ZS8q/dist-types/octokit.d.ts"
    at https://esm.sh/v135/octokit@4.0.2/X-ZS8q/dist-types/octokit.d.ts:4:59
$
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This seems like an issue with `esm.sh` not resolving the import map

That import path is defined in `package.json`
https://unpkg.com/browse/@octokit/core@6.1.2/package.json (Line 67)

**Comment by thisguycodes** [comment]
I honestly don't know if I'm doing something wrong, I also [opened an issue with esm.sh](https://github.com/esm-dev/esm.sh/issues/916) about a bug with their deno cli integration, and they told me they're deprecating it, so maybe it's got something to do with the way that added it to my import map?

here's what my import map looks like:
```json
  "imports": {
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",
    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
    "mock-fetch/": "https://deno.land/x/mock_fetch@0.3.0/",
    "@octokit/webhooks-types": "https://esm.sh/v135/@octokit/webhooks-types@7.6.1",
    "octokit": "https://esm.sh/v135/*octokit@4.0.2",
    "@std/testing": "jsr:@std/testing@^1.0.5"
  },
  "scopes": {
    "https://esm.sh/v135/": {
      "@octokit/app": "https://esm.sh/v135/@octokit/app@15.1.1",
      "@octokit/core": "https://esm.sh/v135/@octokit/core@6.1.2",
      "@octokit/oauth-app": "https://esm.sh/v135/@octokit/oauth-app@7.1.3",
      "@octokit/plugin-paginate-graphql": "https://esm.sh/v135/@octokit/plugin-paginate-graphql@5.2.4",
      "@octokit/plugin-paginate-rest": "https://esm.sh/v135/@octokit/plugin-paginate-rest@11.3.5",
      "@octokit/plugin-rest-endpoint-methods": "https://esm.sh/v135/@octokit/plugin-rest-endpoint-methods@13.2.6",
      "@octokit/plugin-retry": "https://esm.sh/v135/@octokit/plugin-retry@7.1.2",
      "@octokit/plugin-throttling": "https://esm.sh/v135/@octokit/plugin-throttling@9.3.2",
      "@octokit/request-error": "https://esm.sh/v135/@octokit/request-error@6.1.5",
      "@octokit/types": "https://esm.sh/v135/@octokit/types@13.6.1"
    }
  }

```

**Comment by thisguycodes** [comment]
@wolfy1339 I notice you linked the @octokit/core package.json, but the error is saying it's not defined in the octokit package, is octokit somehow supposed to inherit the import map from @octokit/core?

(I genuinely have no idea how these things work)

**Comment by wolfy1339** [comment]
The `octokit` module is built on multiple other Octokit libraries packaged together, like `@octokit/core`, `@octokit/app`, `@octokit/webhooks`.

Sorry, I meant export map
https://nodejs.org/api/packages.html#exports

It defines the exports of that package, in that case, there's 2 exports.
`./` is the main entrypoint
`./types` is a special entrypoint to access some types not exported in the main entrypoint but needed elsewhere.

The problem lies with esm.sh not using the export map in order to map the import to the correct file.

In the mean time, try adding the following to your scopes
```json
"@octokit/core/types": "https://esm.sh/v135/@octokit/core@6.1.2/dist-types/types.d.ts",
```

Also, to prevent any type errors ditch the `@octokit/webhooks-types` package in favour of the `@octokit/openapi-webhooks-types` package. The former are not compatible with v4 of Octokit

**Comment by wolfy1339** [comment]
Closing as there is nothing else actionable for Octokit itself

**Comment by thisguycodes** [comment]
@wolfy1339 thanks for the workaround. Though it seems this just moved on to something else :(
```shell
$ deno check test.ts
error: Failed resolving types. Relative import path "node" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/@octokit/types@13.6.0/dist-types/RequestRequestOptions.d.ts"
    at https://esm.sh/v135/@octokit/types@13.6.0/dist-types/RequestRequestOptions.d.ts:1:22
```

it genuinely seems like I'm the only one doing this...

**Comment by wolfy1339** [comment]
please try to force it to use version 13.6.1 of @octokit/types

**Comment by thisguycodes** [comment]
my scopes already has this:
```json
"@octokit/types": "https://esm.sh/v135/@octokit/types@13.6.1"
```

I seriously don't know how to do what you're asking

**Comment by wolfy1339** [comment]
Nevermind that. It's esm.sh keeping an old version of `@octokit/types` around

As for that error you are getting, it's TypeScript trying to shoehorn NodeJS typings into the project.
The issue seems to stem from `AbortSignal` which is not a Node specific API

The line in question is the following (https://unpkg.com/browse/@octokit/types@13.6.0/dist-types/RequestRequestOptions.d.ts)
```ts
/// <reference types="node" resolution-mode="require"/>
```

**Comment by wolfy1339** [comment]
Will be fixed by https://github.com/octokit/types.ts/pull/656

**Comment by ThisGuyCodes** [comment]
> Also, to prevent any type errors ditch the @octokit/webhooks-types package in favour of the @octokit/openapi-webhooks-types package. The former are not compatible with v4 of Octokit
Can you elaborate a bit more? I use this package like this:

```js
import { WebhookEvent } from "@octokit/webhooks-types";

const handleWebhook = (payload) => {
  const event = payload as WebhookEvent;

  // type narrowing via stuff like this:
  if ("state" in event) {
    // TypeScript now considers event to be of type `StatusEvent`
  }
}
```

I can't figure out how to solve for my needs with @octokit/openapi-webhooks-types

**Comment by thisguycodes** [comment]
> Also, to prevent any type errors ditch the @octokit/webhooks-types package in favour of the @octokit/openapi-webhooks-types package. The former are not compatible with v4 of Octokit

@wolfy1339 Can you elaborate a bit more? I use this package like this:

```js
import { WebhookEvent } from "@octokit/webhooks-types";

const handleWebhook = (payload) => {
  const event = payload as WebhookEvent;

  // type narrowing via stuff like this:
  if ("state" in event) {
    // TypeScript now considers event to be of type `StatusEvent`
  }
}
```

I can't figure out how to solve for my needs with @octokit/openapi-webhooks-types

**Comment by wolfy1339** [comment]
See https://github.com/octokit/webhooks.js/releases/tag/v13.0.0

The types were completely redone and are not compatible.

```ts
import type { webhooks as OpenAPIWebhooks } from "@octokit/openapi-webhooks-types";
export type WebhookEventDefinition<TEventName extends keyof OpenAPIWebhooks> =
  OpenAPIWebhooks[TEventName]["post"]["requestBody"]["content"]["application/json"];
export type StatusEvent = WebhookEventDefinition<"status">;
```
I am working on making a transition package that drops in and replaces `@octokit/webhooks-types` and will resolve everything into friendlier types

**Comment by wolfy1339** [comment]
Try using [`@octokit/openapi-webhooks-types-transition`](https://github.com/octokit/openapi-webhooks/tree/main/packages/openapi-webhooks-types-transition)

**Comment by thisguycodes** [comment]
@wolfy1339 works perfect with no other code changes! ❤️

**Comment by wolfy1339** [comment]
@ThisGuyCodes 
I managed to get `deno check` to work using the following import map
```json
"scopes": {
    "https://esm.sh/v135/": {
      "@octokit/app": "https://esm.sh/v135/@octokit/app@15.1.1?deps=@octokit/types@13.6.2",
      "@octokit/core": "https://esm.sh/v135/@octokit/core@6.1.2?deps=@octokit/types@13.6.2",
      "@octokit/core/types": "https://esm.sh/v135/@octokit/core@6.1.2/dist-types/types.d.ts",
      "@octokit/oauth-app": "https://esm.sh/v135/@octokit/oauth-app@7.1.3?deps=@octokit/types@13.6.2",
      "@octokit/plugin-paginate-graphql": "https://esm.sh/v135/@octokit/plugin-paginate-graphql@5.2.4?deps=@octokit/types@13.6.2",
      "@octokit/plugin-paginate-rest": "https://esm.sh/v135/@octokit/plugin-paginate-rest@11.3.6?deps=@octokit/types@13.6.2",
      "@octokit/plugin-rest-endpoint-methods": "https://esm.sh/v135/@octokit/plugin-rest-endpoint-methods@13.2.6?deps=@octokit/types@13.6.2",
      "@octokit/plugin-retry": "https://esm.sh/v135/@octokit/plugin-retry@7.1.2?deps=@octokit/types@13.6.2",
      "@octokit/plugin-throttling": "https://esm.sh/v135/@octokit/plugin-throttling@9.3.2?deps=@octokit/types@13.6.2",
      "@octokit/request-error": "https://esm.sh/v135/@octokit/request-error@6.1.5?deps=@octokit/types@13.6.2",
      "@octokit/types": "https://esm.sh/v135/@octokit/types@13.6.2",
      "@octokit/request": "https://esm.sh/v135/@octokit/request@9.1.3?deps=@octokit/types@13.6.2",
      "@octokit/graphql": "https://esm.sh/v135/@octokit/graphql@8.1.1?deps=@octokit/types@13.6.2",
      "before-after-hook": "https://esm.sh/v135/before-after-hook@3.0.2"
    }
  }
  ```
I had to add the dependency override for esm.sh, as documented here: https://esm.sh/#specifying-dependencies

The esm.sh deno thingy missed adding `@octokit/graphql`, `before-after-hook` and `@octokit/request`

**Comment by wolfy1339** [comment]
We still have this issue to contend with, https://github.com/esm-dev/esm.sh/issues/995.

I got rid of all `@types/node` on the Octokit side of things

I got `deno check` to work:
```json
{
  "imports": {
    "octokit": "https://esm.sh/v135/*octokit@4.1.0?target=deno",
    "_http_agent": "node:_http_agent",
    "_http_client": "node:_http_client",
    "_http_common": "node:_http_common",
    "_http_incoming": "node:_http_incoming",
    "_http_outgoing": "node:_http_outgoing",
    "_http_server": "node:_http_server",
    "_stream_duplex": "node:_stream_duplex",
    "_stream_passthrough": "node:_stream_passthrough",
    "_stream_readable": "node:_stream_readable",
    "_stream_transform": "node:_stream_transform",
    "_stream_wrap": "node:_stream_wrap",
    "_stream_writable": "node:_stream_writable",
    "_tls_common": "node:_tls_common",
    "_tls_wrap": "node:_tls_wrap",
    "assert": "node:assert",
    "assert/strict": "node:assert/strict",
    "async_hooks": "node:async_hooks",
    "buffer": "node:buffer",
    "child_process": "node:child_process",
    "cluster": "node:cluster",
    "console": "node:console",
    "constants": "node:constants",
    "crypto": "node:crypto",
    "dgram": "node:dgram",
    "diagnostics_channel": "node:diagnostics_channel",
    "dns": "node:dns",
    "dns/promises": "node:dns/promises",
    "domain": "node:domain",
    "events": "node:events",
    "fs": "node:fs",
    "fs/promises": "node:fs/promises",
    "http": "node:http",
    "http2": "node:http2",
    "https": "node:https",
    "inspector": "node:inspector",
    "inspector/promises": "node:inspector/promises",
    "module": "node:module",
    "net": "node:net",
    "os": "node:os",
    "path": "node:path",
    "path/posix": "node:path/posix",
    "path/win32": "node:path/win32",
    "perf_hooks": "node:perf_hooks",
    "process": "node:process",
    "punycode": "node:punycode",
    "querystring": "node:querystring",
    "readline": "node:readline",
    "readline/promises": "node:readline/promises",
    "repl": "node:repl",
    "stream": "node:stream",
    "stream/consumers": "node:stream/consumers",
    "stream/promises": "node:stream/promises",
    "stream/web": "node:stream/web",
    "string_decoder": "node:string_decoder",
    "sys": "node:sys",
    "timers": "node:timers",
    "timers/promises": "node:timers/promises",
    "tls": "node:tls",
    "trace_events": "node:trace_events",
    "tty": "node:tty",
    "url": "node:url",
    "util": "node:util",
    "util/types": "node:util/types",
    "v8": "node:v8",
    "vm": "node:vm",
    "wasi": "node:wasi",
    "worker_threads": "node:worker_threads",
    "zlib": "node:zlib"
  },
  "scopes": {
    "https://esm.sh/v135/": {
      "@octokit/app": "https://esm.sh/v135/@octokit/app@15.1.2?target=deno",
      "@octokit/auth-app": "https://esm.sh/v135/@octokit/auth-app@7.1.4?target=deno",
      "@octokit/auth-unauthenticated": "https://esm.sh/v135/@octokit/auth-unauthenticated@6.1.1?target=deno",
      "@octokit/core": "https://esm.sh/v135/@octokit/core@6.1.3?target=deno",
      "@octokit/core/types": "https://esm.sh/v135/@octokit/core@6.1.3/dist-types/types.d.ts?target=deno",
      "@octokit/oauth-app": "https://esm.sh/v135/@octokit/oauth-app@7.1.5?target=deno",
      "@octokit/plugin-paginate-graphql": "https://esm.sh/v135/@octokit/plugin-paginate-graphql@5.2.4?deps=@octokit/core@6.1.3",
      "@octokit/plugin-paginate-rest": "https://esm.sh/v135/@octokit/plugin-paginate-rest@11.4.0?target=deno",
      "@octokit/plugin-rest-endpoint-methods": "https://esm.sh/v135/@octokit/plugin-rest-endpoint-methods@13.3.0?target=deno",
      "@octokit/plugin-retry": "https://esm.sh/v135/@octokit/plugin-retry@7.1.3?target=deno",
      "@octokit/plugin-throttling": "https://esm.sh/v135/@octokit/plugin-throttling@9.4.0?target=deno",
      "@octokit/request-error": "https://esm.sh/v135/@octokit/request-error@6.1.6?target=deno",
      "@octokit/types": "https://esm.sh/v135/@octokit/types@13.7.0?target=deno",
      "@octokit/webhooks": "https://esm.sh/v135/@octokit/webhooks@13.4.2?target=deno"
    }
  }
}

```
