### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by hamzaislam** [octokit/octokit.js#333]
Issue occuring behind corporate proxy. When trying to use polymer-cli which depends on this module. 

the hit is being made on to [https://api.github.com/repos/Polymer/app-drawer-template/releases](url)

```
D:\test>polymer init -v app-drawer-template
debug:   got args:
{ args: [ 'init', '-v', 'app-drawer-template' ] }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command parsed
{ name: 'init',
  options:
   { _all: { verbose: true, name: 'app-drawer-template' },
     global: { verbose: true },
     _none: { name: 'app-drawer-template' } } }
debug:   config read
{ root: 'D:\\ProjectGIT\\tolweb-mobile-new',
  entrypoint: 'D:\\ProjectGIT\\tolweb-mobile-new\\index.html',
  fragments: [],
  inputs: [ 'D:\\ProjectGIT\\tolweb-mobile-new\\index.html' ] }
debug:   Running command...
debug:   creating yeoman environment...
info:    Running template app-drawer-template
debug:   Running generator polymer-init-app-drawer-template:app
info:    Downloading latest release of Polymer/app-drawer-template
error:   Could not download release from Polymer/app-drawer-template
error:   Uncaught exception: certificate has expired
error:   Error: certificate has expired
    at Object.proto.sendError (D:\node\node_modules\polymer-cli\node_modules\git
hub\api\v3.0.0\index.js:30:19)
    at D:\node\node_modules\polymer-cli\node_modules\github\api\v3.0.0\releases.
js:39:29
    at callCallback (D:\node\node_modules\polymer-cli\node_modules\github\index.
js:743:17)
    at ClientRequest.<anonymous> (D:\node\node_modules\polymer-cli\node_modules\
github\index.js:809:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
```

**Comment by hamzaislam** [comment]
Can someone help?

**Comment by hamzaislam** [comment]
Wasn't a certificate issue, was somehow hitting my local server on 8080 which had an expired cert, due to the proxy URL being interpreted differently on DOS as compared to Cygwin. 
Still unable to hit api.github.com, what's the correct format to set http_proxy and https_proxy?
