### ISSUE TITLE
Cannot find module './api/vundefined' - npm install

### ISSUE THREAD

**Issue by Darker** [octokit/octokit.js#411]
After installing this library over `npm`, I get the following error during instantiation:

```
Error: Cannot find module './api/vundefined'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at new module.exports (D:\web\node_modules\node-github\index.js:180:15)
    at Object.<anonymous> (D:\web\github\start_repo_here.js:37:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

The instantiation code:

```
var github = new GitHub({
    // optional
    debug: true,
    protocol: "https",
    host: "api.github.com", // should be api.github.com for GitHub
    pathPrefix: "", // for some GHEs; none for GitHub
    headers: {
        "user-agent": "Github-Command-Line; start_repo_here; Node.js; lib: mikedeboer/node-github" // GitHub is happy with a unique user agent
    },
    Promise: require('bluebird'),
    followRedirects: false, // default: true; there's currently an issue with non-get redirects, so allow ability to disable follow-redirects
    timeout: 10000
});
```

**Comment by Darker** [comment]
A workaround commandline:

   node_modules\node-github\api>mklink /D vundefined "v3.0.0"

Creates symbolic link to the last version. Windows only, but linux command would be similar.

**Comment by kaizensoze** [comment]
Did you npm install `github` or `node-github`? Unfortunately there's a very much outdated `node-github` npm package that I cannot remove myself. See #141.

**Comment by Darker** [comment]
Yeah, that was the problem. Thanks.
