### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by NealST** [octokit/octokit.js#679]
This is my githubapi options set

```js
let github = new githubApi({
  timeout: 5000,
  host: 'api.github.com', // should be api.github.com for GitHub
  pathPrefix: '/api/v3', // for some GHEs; none for GitHub
  protocol: 'https',
  port: 9898,
  rejectUnauthorized: true // default: true
})
```

when I invoke '**github.repos.create**' function, I got a request timeout error result as follows

```
{ Error: Request timeout
    at ClientRequest.<anonymous> (/Users/mozheng/projects/github-cli/node_modules/github/lib/index.js:770:22)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at TLSSocket.emitTimeout (_http_client.js:722:34)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:398:8)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
  defaultMessage: 'Gateway Timeout',
  message: 'Request timeout',
  code: '504',
  status: 'Gateway Timeout',
  headers: undefined }
```

I have no idea how to fix this problem, so I want to look for help from you

**Comment by machour** [comment]
Hi @NealST, if you're indeed targeting `api.github.com`, you shouldn't be `pathPrefix` and set the port to `443`. In fact, you can remove all these options and simply use 

    let github = new githubApi(};
