### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by iamnewton** [octokit/octokit.js#727]
I'm pretty sure I'm doing something wrong here, but I've exhausted what it is.

```
const octokit = require('@octokit/rest')({
    debug: true,
    host: 'github.<company domain>.com',
    pathPrefix: '/api/v3'
});

octokit.authenticate({
    type: 'token',
    token: '<personal access token with all scopes'
});

octokit.orgs.get({org: '<valid org>'}, (error, result) => {
    console.log(error);
});
```

Output:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (./node_modules/@octokit/rest/lib/request/request.js:79:31)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by gr2m** [comment]
the `debug` option has been removed in an earlier release. Could you run the script with `DEBUG=octokit*` and paste the logs here?

Just to make sure I tried to reproduce the problem against GitHub’s API (default setting) and with that it all looks good: https://runkit.com/gr2m/5a710542399a8600123e8f5f

**Comment by iamnewton** [comment]
```
#19445: $ node bin/set-status.js
  octokit:rest REQUEST: Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'github.<company domain>.com',
  port: null,
  hostname: 'github.<company domain>.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/api/v3/orgs/<valid org>',
  path: '/api/v3/orgs/<valid org>',
  href: 'https://github.<company domain>.com/api/v3/orgs/<valid org>',
  method: 'get',
  body: undefined,
  headers:
   { accept: 'application/vnd.github.v3+json',
     'user-agent': 'octokit/rest.js v14.0.7',
     authorization: 'token <personal access token with all scopes>' },
  ca: undefined,
  family: undefined,
  proxy: undefined,
  rejectUnauthorized: true,
  timeout: 0 } +0ms
  octokit:rest STATUS: 200 +264ms
  octokit:rest HEADERS: {"server":"GitHub.com","date":"Tue, 30 Jan 2018 23:55:19 GMT","content-type":"application/json; charset=utf-8","content-length":"1458","connection":"close","status":"200 OK","cache-control":"private, max-age=60, s-maxage=60","vary":"Accept, Authorization, Cookie, X-GitHub-OTP","etag":"\"8c3d8a209b545d95c46555c4d1451fcd\"","last-modified":"Tue, 07 Nov 2017 19:20:21 GMT","x-oauth-scopes":"admin:gpg_key, admin:org, admin:org_hook, admin:pre_receive_hook, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user","x-accepted-oauth-scopes":"admin:org, read:org, repo, user, write:org","x-github-media-type":"github.v3; format=json","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","x-github-request-id":"d65b47d0-0f84-4ee0-af70-0d61a64a2706","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","x-runtime-rack":"0.045419"} +0ms
undefined:1
{"login":"<valid org>","id":316,"url":"https://github.rp<company domain>.com/api/v3/orgs/<valid org>","repos_url":"https://github.<company domain>.com/api/v3/orgs/<valid org>/repos","events_url":"https://github.<company domain>.com/api/v3/orgs/<valid org>/eve


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (./node_modules/@octokit/rest/lib/request/request.js:79:31)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by gr2m** [comment]
What GHE version are you using?

it’s weird that the logged JSON response is cut off

```
{"login":"<valid org>","id":316,"url":"https://github.rp<company domain>.com/api/v3/orgs/<valid org>","repos_url":"https://github.<company domain>.com/api/v3/orgs/<valid org>/repos","events_url":"https://github.<company domain>.com/api/v3/orgs/<valid org>/eve
```

could you add a console log before the JSON.parse in `./node_modules/@octokit/rest/lib/request/request.js:77` and see what `data` looks like before it’s passed to `JSON.parse`?

**Comment by iamnewton** [comment]
2.11

**Comment by iamnewton** [comment]
gets the same error

**Comment by iamnewton** [comment]
```
#15452: $ node -v
v9.2.0

#15437: $ npm -v
5.5.1
```

**Comment by gr2m** [comment]
The error is coming from this line

https://github.com/octokit/rest.js/blob/5197a6e5f1e2e455be0c8e1d81fa1b68b2215a5e/lib/request/request.js#L78-L80

change it to 

```js
        if (contentType && contentType.indexOf('application/json') !== -1) {
          console.log(data)
          data = data && JSON.parse(data)
        }
```

and see what the logged data looks like?

**Comment by iamnewton** [comment]
Did that, it's getting the same error.

**Comment by gr2m** [comment]
ah I’m sorry, I misunderstood your previous comment.

So that is very odd, it looks like the GHE instance returns a 200 status code for an error.

Could you please try to install `github` and then replace

```diff
- const octokit = require('@octokit/rest')
+ const octokit = require('@github')
```

I want to make sure that this is not a regression from the refactoring that we did before renaming the module.

I'll meanwhile try to get a GHE 2.11 instance setup to reproduce the error. 
I’d be happy to pair on this, too, if you like?

**Comment by gr2m** [comment]
I’m still waiting for a license to reproduce the issue myself, I’ll keep you posted here. Could you find out anything on your site?

**Comment by gr2m** [comment]
@chrisopedia I’m sorry, I’m still waiting :( Any luck on your side to figure out the problem?

**Comment by iamnewton** [comment]
None yet.

**Comment by gr2m** [comment]
could you please give it a try with https://github.com/octokit/rest.js/pull/743?

**Comment by gr2m** [comment]
I assume it’s working now or is no longer an issue. Please let me know if it still is

**Comment by iamnewton** [comment]
Still not working. Sorry took me so long to get back to you.  But I think it might be based on authentication at this point.

```
(node:50767) UnhandledPromiseRejectionWarning: HttpError: invalid json response body at https://github.<domain>.com/api/v3/orgs/<org>/repos?type=public reason: Unexpected end of JSON input```

**Comment by gr2m** [comment]
No worries!

It would be pretty great to see the response from the server. Any chance you could send a `curl` request and see what the server responds with?

**Comment by iamnewton** [comment]
so here's the code:

```js
const octokit = require('@octokit/rest')({
	timeout: 0, // 0 means no request timeout
	headers: {
		accept: 'application/vnd.github.v3+json',
		'user-agent': 'octokit/rest.js v1.2.3' // v1.2.3 will be current version
	},

	// custom GitHub Enterprise URL
	baseUrl: 'https://github.<domain>.com/api/v3',

	// Node only: advanced request options can be passed as http(s) agent
	agent: undefined
});

octokit.authenticate({
    type: 'token',
    token: '<valid token>'
});

// Compare: https://developer.github.com/v3/repos/#list-organization-repositories
octokit.repos.getForOrg({
	org: 'frontendgine',
	type: 'public'
}).then(result => {
	console.log(result);
}).catch(err => {
	console.log(err);
});
```

That results in this:

```bash
#27775: $ node index.js
{ HttpError: invalid json response body at https://github.<domain>.com/api/v3/orgs/frontendgine/repos?type=public reason: Unexpected end of JSON input
    at fetch.then.then.catch.error (/Users/chrisopedia/Code/frontendgine/legion/develop-cli/node_modules/@octokit/rest/lib/request/request.js:96:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  name: 'HttpError',
  code: 500,
  status: 'Internal Server Error',
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'cache-control': 'private, max-age=60, s-maxage=60',
     connection: 'close',
     'content-length': '62291',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Tue, 08 May 2018 00:03:07 GMT',
     etag: '"062eaf29f60862e9e6472bcc13db7bfd"',
     server: 'GitHub.com',
     status: '200 OK',
     'strict-transport-security': 'max-age=31536000; includeSubdomains',
     vary: 'Accept, Authorization, Cookie, X-GitHub-OTP',
     'x-accepted-oauth-scopes': 'repo',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'c10c071d-e323-4d41-b379-9f64eb12619e',
     'x-oauth-scopes': 'admin:gpg_key, admin:org, admin:org_hook, admin:pre_receive_hook, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user',
     'x-runtime-rack': '0.075020',
     'x-xss-protection': '1; mode=block' } }
```

**Comment by iamnewton** [comment]
Looks like its trying to access `GitHub.com` and not my enterprise domain.

**Comment by iamnewton** [comment]
My suspect was right.  When I went through the source code and changed the `baseUrl` to my hosted endpoint, the data comes back correct without errors.

[Here](https://github.com/octokit/rest.js/blob/master/lib/endpoint/defaults.js#L5) and [here](https://github.com/octokit/rest.js/blob/master/lib/defaults.js#L7)

**Comment by gr2m** [comment]
closing, as discussed with @chrisopedia.
