### ISSUE TITLE
octokit.activity.getNotifications throws error

### ISSUE THREAD

**Issue by JuanCaicedo** [octokit/octokit.js#832]
I'm calling this method passing it only a `since` parameter, like
```js
octokit.activity.getNotifications({ since: '2018-04-06T20:04:47.000Z' })
```
And I'm getting the following error
```
TypeError: Cannot read property 'url' of undefined
    at httpRequest (/Users/juan/code/gh-notifications/gh-note-api/node_modules/@octokit/rest/lib/request/request.js:18:30)
    at restRequest (/Users/juan/code/gh-notifications/gh-note-api/node_modules/@octokit/rest/lib/request/index.js:9:10)
    at /Users/juan/code/gh-notifications/gh-note-api/node_modules/before-after-hook/lib/register.js:38:12
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

To me this seems like it's a bug inside the library, would you agree? I'm working on some debugging now, I can add any new information I find

**Comment by JuanCaicedo** [comment]
My apologies, I think I had something wrong in my dev environment 😅
