### ISSUE TITLE
Error: 'github' has been renamed to '@octokit/rest'

### ISSUE THREAD

**Issue by zeke** [octokit/octokit.js#847]
We have a project that hasn't migrated from `github` to `@octokit/rest` yet. We're running version 14. I expected to see the deprecation warning on install, but didn't not expect an error. Is this intended behavior?

Note: this is not on fire. We solved it by pinning to `github@13.0.0`, and we'll soon migrate to the new module.

https://github.com/electron/i18n/issues/327

```
$ npm run collect

> electron-i18n@0.0.0-development collect /Users/z/git/electron/i18n
> node script/collect.js

/Users/z/git/electron/i18n/node_modules/github/index.js:1
(function (exports, require, module, __filename, __dirname) { throw new Error("'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)")
                                                              ^

Error: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
    at Object.<anonymous> (/Users/z/git/electron/i18n/node_modules/github/index.js:1:69)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/z/git/electron/i18n/script/collect.js:14:16)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-i18n@0.0.0-development collect: `node script/collect.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-i18n@0.0.0-development collect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/z/.npm/_logs/2018-05-02T16_46_21_502Z-debug.log
```

**Comment by gr2m** [comment]
> We have a project that hasn't migrated from `github` to `@octokit/rest` yet. We're running version 14. I expected to see the deprecation warning on install, but didn't not expect an error. Is this intended behavior?

Yes, we have deprecation warnings for the previous version for quite a while. Eventually we published `github@14.0.0` so that people won’t get stuck at an old version. You can install `@octokit/rest@^14.0.0` instead, it's the same code, just the new name
